 platform :ios, '8.0'

target 'Demo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Demo
pod 'AFNetworking'
pod 'MJExtension'
pod 'MJRefresh'
pod 'SVProgressHUD'
pod 'Masonry'
pod 'SDWebImage'

end
